tasks:
  - init: yarn --cwd /workspace/nlw-2-proffy/leo/web
    command: yarn --cwd /workspace/nlw-2-proffy/leo/web start
  - openMode: split-right
  - openIn: right
    command: yarn --cwd /workspace/nlw-2-proffy/leo/server
    command: yarn --cwd /workspace/nlw-2-proffy/leo/server start
    
