tasks:
  - init: yarn --cwd /workspace/nlw-2-proffy/leo/web
    command: yarn --cwd /workspace/nlw-2-proffy/leo/server
    command: yarn --cwd /workspace/nlw-2-proffy/leo/web start
    command: yarn --cwd /workspace/nlw-2-proffy/leo/server start
    
